---
- name:
  hosts: all
  gather_facts: yes
  tasks:
    - debug:
        var: ansible_enp0s8.ipv4.address
    - name: create hosts
      template:
        src: ../templates/hosts.j2
        dest: /etc/myhosts
      when: inventory_hostname in groups['prod']