---
- name: http stuff
  hosts: dev, prod
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Enable Start httpd
      service:
        name: httpd
        state: started
      
    - name: Add FW port
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      loop:
        - http
        - https
      
    - name: Enable and Start Services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld

    - name: Deply Index file
      template:
        src: ../templates/http.j2
        dest: /var/www/html/index.html