---
- name: Register with RHN
  hosts: node-05
  tasks:
    - name: Register
      redhat_subscription:
        username:
        password:
        auto_attach: yes
        state: present
        force_register: yes
