---
- name: web
  hosts: dev
  become: yes
  tasks:
    - name: mkdir
      file:
        path: /webdev
        state: directory
        group: apache
        mode: 02775
        #setype: httpd_sys_content_t

    - name: link
      file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link
        force: yes

    - name: index
      copy:
        content: "Development\n"
        dest: /webdev/index.html
        #setype: httpd_sys_content_t

#    - name: selinux
#      sefcontext:
#        path: "/webdev(/.*)?"
#        setype: httpd_sys_content_t


# curl http://node-01/webdev/ (not the trailing /)