---
- name: webdev
  hosts: dev, prod
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Add FW port
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      loop:
        - http
        - https
      
    - name: Enable and Start Services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld
    
    - name: create /var/www/html/webdev
      file:
        path: /webdev
        state: directory

    - name: create webdev
      file:
        path: /webdev
        state: directory
        mode: 02775
        owner: root
        group: root

    - name: Create link
      file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link
        force: yes

    - name: Deply Index file
      template:
        src: ../templates/http.j2
        dest: /webdev/index.html

    - name: SELinux
      sefcontext:
        path: "/webdev(/.*)?"
        setype: httpd_sys_content_t
        state: present